config/routes.rb
Rails.application.routes.draw do

  root to: "series#index"

  resources :series, only: [:index, :show], param: :id do
  	resources :seasons, only: [:index, :show], param: :id
  end
 
  resources :episodes, only: [:show], param: :id
  resources :characters, only: [:show], param: :id

  get '/search' => 'pages#search', :as => 'search_page'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  
  def initialize(id, name, occupation, img, status, nickname, appearance, better_call_saul_appearance, portrayed, category)
    @id = id
    @name = name
    @occupation = occupation
    @img = img
    @status = status
    @nickname = nickname
    @appearance = appearance
    @better_call_saul_appearance = better_call_saul_appearance
    @portrayed = portrayed
    @category = category
  end
  
  def id
    @id
  end

  def name
    @name
  end

  def occupation
    @occupation
  end

  def img
    @img
  end

  def status
    @status
  end

  def nickname
    @nickname
  end

  def appearance
    @appearance
  end

  def better_call_saul_appearance
    @better_call_saul_appearance
  end

  def portrayed
    @portrayed
  end

  def category
    @category
  end
end

app/models/episode.rb
class Episode
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  
  def initialize(episode_id, title, season, episode, air_date, characters, series)
    @episode_id = episode_id
    @title = title
    @season = season
    @episode = episode
    @air_date = air_date
    @characters = characters
    @series = series
  end
  

  def episode_id
    @episode_id
  end

  def title
    @title
  end

  def season
    @season
  end

  def episode
    @episode
  end

  def air_date
    @air_date
  end

  def characters
    @characters
  end

  def series
    @series
  end
end

app/models/season.rb
class Season
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  def initialize(season_n) 
    @episodes = episodes
  end
  
  def persisted?
    false
  end
end

app/models/serie.rb
class Serie
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  def initialize(name, n_seasons)

    @name = name
    @n_seasons = n_seasons
  end
  
  def name
    @name
  end

  def n_seasons
    @n_seasons
  end


  def persisted?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def show
  	response = HTTP.get('https://tarea-1-breaking-bad.herokuapp.com/api/characters/' + params[:id])
  	c = (JSON.parse response.body)[0]
  	@char = Character.new(c["id"], c["name"], c["occupation"], c["img"], c["status"], c["nickname"],
  						c["appearance"], c["better_call_saul_appearance"], c["portrayed"], c["category"])
  	
	response = HTTP.get('https://tarea-1-breaking-bad.herokuapp.com/api/quote?author=' + c["name"].gsub(' ', '+'))
	@quotes = (JSON.parse response.body)

  end

end

app/controllers/episodes_controller.rb
require 'http'
require 'json'

class EpisodesController < ApplicationController

  def show
  	response = HTTP.get('https://tarea-1-breaking-bad.herokuapp.com/api/episodes/' + params[:id])
  	e = (JSON.parse response.body)[0]
  	@episode = Episode.new(e["episode_id"], e["title"], e["season"], e["episode"], e["air_date"], e["characters"], e["series"])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end

  def search 
    #codigo sacado de https://melvinchng.github.io/rails/SearchFeature.html#43-adding-a-simple-search-feature
    if params[:search].blank?  
      redirect_to(root_path, alert: "Empty field!") and return  
    else  
      response = HTTP.get('https://tarea-1-breaking-bad.herokuapp.com/api/characters?name=' + params[:search].downcase.gsub(' ','+'))
      puts response.code
      puts response.body
      @characters = (JSON.parse response.body)
    end
  end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController

  def show
  	response = HTTP.get('https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=' + params[:series_id])
  	json_episodes = JSON.parse response.body
  	@episodes = Array.new
  	for e in json_episodes
  		if e['season'] == params[:id]
  			episode = Episode.new(e["episode_id"], e["title"], e["season"], e["episode"], e["air_date"], e["charactersarray"], e["series"])
  			@episodes.push(episode)
  		end
  	@episodes.sort_by { |e| [e.episode] }
  	end

  end
end

app/controllers/series_controller.rb
require 'http'
require 'json'

class SeriesController < ApplicationController
  def index
  end

  def show
  	
  	response = HTTP.get('https://tarea-1-breaking-bad.herokuapp.com/api/episodes?series=' + params[:id])
  	episodes = JSON.parse response.body
  	lower = episodes[0]['season'].to_i
  	higher = episodes[0]['season'].to_i

  	for episode in episodes
  		lower =  episode['season'].to_i < lower ? episode['season'].to_i : lower
  		higher =  episode['season'].to_i > higher ? episode['season'].to_i : higher
  	end
  	@serie = Serie.new(params[:id], higher.to_i)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
	def find_character_id(name)
    	response = HTTP.get("https://tarea-1-breaking-bad.herokuapp.com/api/characters?name=#{name.gsub(' ','+')}")
    	puts name.gsub(' ','+')
    	puts response.code
    	character = JSON.parse response.body
  		return character[0]['char_id']
  	end
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/characters/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

<h1 class="title">Informacion de Personaje</h1>

<%= "name: #{@char.name}" %> <br>
<td> <%= "nickname: #{@char.nickname}" %> <br> </td> 
<td> <%= "status: #{@char.status}" %> <br> </td> 
<td> <%= "portrayed: #{@char.portrayed}" %> <br> </td> 
<td> <%= "Series en las que aparece: #{@char.category}" %> <br> </td> 
<td> <%= image_tag @char.img , size: '150' %> <br><br></td>

</tr>

<p> Frases del Personaje </p>

<% @quotes.each do |q| %>
  <tr>
    <%= q['quote'] %> <br>
  </tr>
<% end %>

<br>
<br>
<p> Temporadas de Breaking Bad en la que aparece </p>
<% @char.appearance.each do |season| %>
  <tr>
    <td><%= link_to "Season #{season}", series_season_path('Breaking+Bad', season) %>
  </tr>
<% end %>


<p> Temporadas de Better Call Saul en la que aparece </p>
<% @char.better_call_saul_appearance.each do |season| %>
  <tr>
    <td><%= link_to "Season #{season}", series_season_path('Better+Call+Saul', season) %>
  </tr>
<% end %>

app/views/episodes/index.html.erb
<h1>Episodes#index</h1>
<p>Find me in app/views/episodes/index.html.erb</p>

app/views/episodes/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

<h1 class="title">Informacion de capítulo</h1>

<%= "Episodio #{@episode.episode}" %> <br>
<%= "Título: #{@episode.title}" %> <br>
<%= "Temporada: #{@episode.season}" %> <br>
<%= "Lanzamiento: #{@episode.air_date}" %> <br>
<%= "Serie: #{@episode.series}" %> <br>

<br>
<br>
<p> Personajes que aparecen en este episodio </p>
<% @episode.characters.each do |char| %>
        <tr>
          <td><%= link_to char, character_path(find_character_id(char)) %>
        </tr>
        <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>T1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


    <%= form_tag(search_page_path, :method => "get",   
      class: 'navbar-form navbar-left') do %>  
        <%= link_to('PÁGINA DE INICIO', root_path, :class => "button is-dark is-outlined") %>
        <div style="width:800px; margin:0 auto;"> 
        <%= search_field_tag :search, params[:search], placeholder: "Nombre de personaje", class: "form-control" %>  
          <%= button_tag "Buscar", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
      </div>  
    <% end %>

    
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

<h1 class="title">Informacion de Breaking bad y Better Call Saul</h1>

<p class="level-item">
    <%= link_to('Breaking Bad', series_index('breaking+bad'), :class => "button is-dark is-outlined") %>
</p>

<p class="level-item">
    <%= link_to('Better Call Saul', series_index('Better+Call+Saul'), :class => "button is-dark is-outlined") %>
</p>

app/views/pages/search.html.erb
<h3>Search Result</h3>  

    <% if @characters.empty? %>
        <p> No se han encotrado resultados para la busqueda, prueba con otra cosa </p>
    <% end %>
    <% @characters.each do |result| %>  
        <tr>
          <td><%= link_to result['name'], character_path(result['char_id']) %> <br>
        </tr>
    <% end %>

app/views/seasons/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

<table class="table is-striped">
      <tr class="th">
        <th>Capitulos de <%= @episodes[0].series %> Temporada <%= @episodes[0].season %></th>
      </tr>
      <% @episodes.each do |e| %>
        <tr>
          <td><%= link_to "#{e.episode}. #{e.title}", episode_path(e.episode_id) %>
        </tr>
      <%end %>
    </table>

app/views/series/index.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

<h1 class="title">Informacion de Breaking bad y Better Call Saul</h1>

<p class="level-item">
    <%= link_to('Temporadas de Breaking Bad', series_path('Breaking+Bad'), :class => "button is-dark is-outlined") %>
</p>

<p class="level-item">
    <%= link_to('Temporadas de Better Call Saul', series_path('Better+Call+Saul'), :class => "button is-dark is-outlined") %>
</p>

app/views/series/show.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">


<h1 class="title">Serie: <%= @serie.name.gsub('+', ' ') %></h1>
    
    <table class="table is-striped">
      <tr class="th">
        <th>Temporada</th>
      </tr>
      <% for i in 1.. @serie.n_seasons %>
        <tr>
          <td><%= link_to 'Temporada %d' % [i], series_season_path(@serie.name, i) %>
        </tr>
      <%end %>
    </table>